db_uri: sqlite:///alphaevolve.db

experiment:
  label: fib-multi-model-v1        # human-readable tag
  notes: "Fibonacci sanity run with multiple models"
  save_top_k: 5               # number of top programs to save one completion of the experiment

llm:
  provider: gemini
  models:
    - name: gemini-2.5-flash
      probability: 0.9
      temperature: 0.8
      llm_timeout: 60.0
    - name: gemini-2.5-pro
      probability: 0.1
      temperature: 0.9
      llm_timeout: 120.0
  retry_model: gemini-2.5-flash-lite # Use the faster model for retries and feedback

evolution:
  population_size: 40
  temperature: 1.5
  max_generations: 20         # keeps PoC run short
  inspiration_count: 4        # number of inspirations to use in each generation
  max_retries: 3              # number of retries for failed program generation
  eval_timeout: 30.0    # timeout in seconds for evaluation runs (0 = no timeout)
  enable_feedback: true       # Enable LLM-generated feedback for successful programs
  # Enhanced inspiration selection parameters
  selection_method: enhanced_inspiration  # Method: "boltzmann", "top_k_and_random", or "enhanced_inspiration"
  recent_generations: 5       # Number of recent generations to consider for inspiration selection
  recent_percentile: 10.0     # Percentile threshold for recent generation selection (0-100)

problem:
  entry_script: examples/fibonacci/solution.py
  evaluator:    examples/fibonacci/evaluate.py
